version: '3'
services:
  dlab-client:
    image: "nginx"
    container_name: dlab-client
    volumes:
      - "./build:/var/www/app"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "3001:80"
